
package com.mousbah.web.service.client.tool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserAdminService", targetNamespace = "http://web.mousbah.com/", wsdlLocation = "file:/C:/Users/Mousbah/workspace/WebUserAdminService/target/generated-sources/wsdl/UserAdminService.wsdl")
public class UserAdminService
    extends Service
{

    private final static URL USERADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERADMINSERVICE_EXCEPTION;
    private final static QName USERADMINSERVICE_QNAME = new QName("http://web.mousbah.com/", "UserAdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Mousbah/workspace/WebUserAdminService/target/generated-sources/wsdl/UserAdminService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERADMINSERVICE_WSDL_LOCATION = url;
        USERADMINSERVICE_EXCEPTION = e;
    }

    public UserAdminService() {
        super(__getWsdlLocation(), USERADMINSERVICE_QNAME);
    }

    public UserAdminService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERADMINSERVICE_QNAME, features);
    }

    public UserAdminService(URL wsdlLocation) {
        super(wsdlLocation, USERADMINSERVICE_QNAME);
    }

    public UserAdminService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERADMINSERVICE_QNAME, features);
    }

    public UserAdminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAdminService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebUserAdminService
     */
    @WebEndpoint(name = "WebUserAdminService")
    public WebUserAdminService getWebUserAdminService() {
        return super.getPort(new QName("http://web.mousbah.com/", "WebUserAdminService"), WebUserAdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebUserAdminService
     */
    @WebEndpoint(name = "WebUserAdminService")
    public WebUserAdminService getWebUserAdminService(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.mousbah.com/", "WebUserAdminService"), WebUserAdminService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERADMINSERVICE_EXCEPTION!= null) {
            throw USERADMINSERVICE_EXCEPTION;
        }
        return USERADMINSERVICE_WSDL_LOCATION;
    }

}
