
package com.mousbah.web.service.client.tool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebUserAdminService", targetNamespace = "http://web.mousbah.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebUserAdminService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web.mousbah.com/WebUserAdminService/authenticateUserRequest", output = "http://web.mousbah.com/WebUserAdminService/authenticateUserResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://web.mousbah.com/WebUserAdminService/authenticateUser/Fault/Exception")
    })
    public boolean authenticateUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

}
